Задача 1. Инициализация рабочего окружения
IAmFunkyFrog/formal-lang-course pull request #1
Opened 2022-09-11 07:49 UTC by IAmFunkyFrog

Выполнено первое домашнее задание "Инициализация рабочего окружения":
- [X] Реализовать модуль, предоставляющий перечисленные ниже возможности:
  - [X] По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах. 
  - [X] По количеству вершин в циклах и именам меток строить граф из двух циклов и сохранять его в указанный файл в формате DOT.
- [X] Добавить необходимые тесты.
- [X] Добавить запуск тестов с помощью `pytest` в `.github/workflows/`.

2022-09-12 17:20 UTC, EgorOrachyov requested changes

2022-09-12 17:20 UTC, EgorOrachyov commented on project/task1.py
> +from dataclasses import dataclass
Файлы необходимо именовать не по заданиям, а по функциональности, которую они предоставляют. Например, в файле утилиты для работы с графами, тогда файл стоит назвать `graph_utils.py` и т.д.

2022-09-12 17:20 UTC, EgorOrachyov commented on tasks/task1.md
Контент папки `tasks/*` модифицировать не требуется. Для отслеживания того, что было сделано достаточно в описание к ревью копировать текст задания и там проставлять крестики. Поэтому изменения в файле надо откатить.

2022-09-12 17:20 UTC, EgorOrachyov commented on tests/test_task1.py
> +import filecmp
Тесты именовать не по заданиям, а логически, по тому, что они тестируют. (В иделае для тестирования отдельной функции/группы функций иметь отдельный тестовый файл)

2022-09-13 06:17 UTC, IAmFunkyFrog commented on project/task1.py
> +from dataclasses import dataclass
Изменил

2022-09-13 06:17 UTC, IAmFunkyFrog commented on tasks/task1.md
Откатил

2022-09-13 06:18 UTC, IAmFunkyFrog commented on tests/test_task1.py
> +import filecmp
Разделил тесты на отдельные файлы. На каждую функцию отдельный файл.

2022-09-14 07:13 UTC, EgorOrachyov requested changes
Откатить изменения в `task1.md`

2022-09-14 07:13 UTC, EgorOrachyov commented on tasks/task1.md
> +- [X] Добавить запуск тестов с помощью `pytest` в `.github/workflows/`.
Что-то осталось

2022-09-14 15:26 UTC, IAmFunkyFrog commented on tasks/task1.md
> +- [X] Добавить запуск тестов с помощью `pytest` в `.github/workflows/`.
Прибрал оставшееся

2022-09-15 07:07 UTC, EgorOrachyov approved these changes

2022-09-16 14:26 UTC, merged