Задача 3. Регулярные запросы для всех пар вершин
IAmFunkyFrog/formal-lang-course pull request #3
Opened 2022-09-25 18:42 UTC by IAmFunkyFrog

- [X] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать **функцию** пересечения двух конечных автоматов через тензорное произведение.
- [X] На основе предыдущей функции реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе.
  - Для конструирования регулярного запроса и преобразований графа использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
- [X] Добавить необходимые тесты.

2022-09-26 17:56 UTC, EgorOrachyov requested changes

2022-09-26 17:56 UTC, EgorOrachyov commented on project/automata_utils.py
> +        self, symbols_to_matrix: dict[Symbol, coo_matrix], states: list[State]
Булева декомпозиция напрашивается в отдельный модуль

2022-09-26 17:56 UTC, EgorOrachyov commented on project/graph_utils.py
> +def regular_path_query(
В отдельный модуль

2022-09-27 14:59 UTC, IAmFunkyFrog commented on project/automata_utils.py
> +        self, symbols_to_matrix: dict[Symbol, coo_matrix], states: list[State]
Выделил boolean_decomposition.py

2022-09-27 15:00 UTC, IAmFunkyFrog commented on project/graph_utils.py
> +def regular_path_query(
Выделил regular_path_query.py

2022-09-27 17:45 UTC, EgorOrachyov approved these changes

2022-09-28 16:24 UTC, merged