Задача 4. Регулярные запросы для нескольких стартовых вершин
IAmFunkyFrog/formal-lang-course pull request #4
Opened 2022-10-02 16:11 UTC by IAmFunkyFrog

- [X] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать **функцию** достижимости с регулярными ограничениями для нескольких стартовых вершин.
  - Предусмотрите два варианта задачи:
    - Для указанного множества стартовых вершин найти множество достижимых.
    - Для каждой вершины из указанного множества найти множество достижимых вершин.
- [X] На основе реализованной функции реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе и вариант решаемой задачи.
  - Для конструирования регулярного запроса и графа использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
- [X] Добавить необходимые тесты.

2022-10-03 19:33 UTC, EgorOrachyov requested changes

2022-10-03 19:33 UTC, EgorOrachyov commented on project/regular_path_query.py
> +        from start_states
Результат выполнения rpq (bfs_rpq) это это иножество вершин графа, либо множество пар вида (i , j), где i, j -- это вершины графа. В этой функции (и в regular_path_query) вы формально возвращаете объект State, что не верно. Необходимо возвращать четсный объект graph node (т.е. делать обратную конвертацию из NFA состояний в вершины графа, т.к. извне мы ожидаем вершины графа только)

2022-10-03 19:33 UTC, EgorOrachyov commented on tests/test_bfs_based_regular_path_query.py
> +    ),
Здесь и далее после рефакторинга заменить State на честные вершины графа. Если такая же ожибка в тестах для задания 3, то в этом же PR поправить для того задания.

2022-10-03 19:33 UTC, EgorOrachyov commented on project/regular_bfs.py
> +    """
В отдельный модуль

2022-10-04 17:51 UTC, IAmFunkyFrog commented on project/regular_path_query.py
> +        from start_states
Поменял на честные вершины

2022-10-04 17:51 UTC, IAmFunkyFrog commented on tests/test_bfs_based_regular_path_query.py
> +    ),
Заменил

2022-10-04 17:51 UTC, IAmFunkyFrog commented on project/regular_bfs.py
> +    """
Создал модуль left_right_matrix.py

2022-10-06 07:52 UTC, EgorOrachyov approved these changes

2022-10-07 11:12 UTC, merged